<!DOCTYPE html>
<html>
    <head>
        <title>Mandrill File Sender</title>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class='container'>
          <?php echo $this->layout()->content; ?>
        </div>
        <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
        <script type='text/javascript'>
        tinymce.init({selector:'textarea'});
        </script>
    </body>
</html>